name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Gera a animação da cobra com base nos commits
      - name: Generate Snake GIF and SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            Dev-Isaque/github-snake.svg
            Dev-Isaque/github-snake-dark.svg?palette=github-dark
            Dev-Isaque/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Display Snake animation link
        run: |
          echo "GitHub Snake has been generated. You can see it here: https://github.com/${{ github.repository_owner }}/Dev-Isaque-files/blob/main/Dev-Isaque/github-snake.svg"
